### ISSUE TITLE
Support retrying as context manager

### ISSUE THREAD

**Issue by odedfos** [rholder/retrying#70]
Would be very helpful to support retrying as a context manager:

Something along the lines of:
```
def do_something_unreliable():
    if random.randint(0, 10) > 1:
        raise IOError("Broken sauce, everything is hosed!!!111one")
    else:
        return "Awesome sauce!"

with retry(wait_fixed=2000):
    do_something_unreliable()
```

**Comment by bersace** [comment]
Looks nice. Do you know how a context manager can loop the with block ?

**Comment by odedfos** [comment]
It probably can't.
Inspired by this [SO](https://stackoverflow.com/questions/16919570/encapsulating-retries-into-with-block) I came up with the following solution:

```
class Retry(object):
    def __init__(self, func, *dargs, **dkw):
        self.func = func

        self.wrapped = retry(*dargs, **dkw)(func)

        self.param_validator = self._make_signature_validator()

    def _make_signature_validator(self):
        argspec = inspect.getargspec(self.func)

        # For bound functions
        if hasattr(self.func, 'im_self') and getattr(self.func, 'im_self'):
            argspec.args.pop(0)

        formatted_args = inspect.formatargspec(*argspec)
        fndef = 'lambda %s: True' % (formatted_args.lstrip('(').rstrip(')'))

        # Generate a function that will validate the params passed to func(). If signatures mismatch it will raise ex.
        param_validator = eval(fndef, {})

        def _validate_func(*args, **kwargs):
            try:
                # We must validate the params before calling the actual function.
                # Failing to do so will raise a TypeError internally which will be treated as a 'valid' exception and will
                # be retried.
                param_validator(*args, **kwargs)
            except TypeError as e:
                raise TypeError(e.message.replace('<lambda>', self.func.__name__))

        return _validate_func

    def __call__(self, *args, **kwargs):
        self.param_validator(*args, **kwargs)

        return self.wrapped(*args, **kwargs)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        pass
```

Then, in order to use it:
```
with Retry(do_something_unreliable, wait_fixed=2000) as retry_unreliable:
    retry_unreliable()
```

What do you think?
It's not as elegant as what I had in mind but still allows a lot of flexibility with the retry params.
If this project is active and the solution acceptable and can open a pull request.

**Comment by bersace** [comment]
Hmm, that's looks more realistic this way ^^

What changes from using decorator ?

``` python
retry_unreliable = retry(wait_fixed=2000)(do_something_unreliable)
retry_unreliable(do_something_arg)
```

**Comment by odedfos** [comment]
Not much, except the validation of the wrapped functions arguments.
Using the decorator directly does not distinguish between the wrapped function failing, and failing to call the function because args are wrong.

In other words, calling a function properly decorated with the wrong arguments will immediately throw a TypeError.
On the other hand, calling the dynamically wrapped function with wrong args will raise the TypeError internally and trigger the defined retry logic in the wrapper which isn't the correct behavior.

Using the contextmanager & inspection I managed to achieve the correct behavior (though it might not be the optimal solution).

**Comment by bersace** [comment]
@odedfos I see the point. I avoid retrying on `TypeError` and pefer to use a curated whitelist of retried exceptions. See https://github.com/novafloss/jenkins-epo/blob/master/jenkins_epo/utils.py#L49-L57

Note, `retrying` is unmaintained, I'm just trying to help you to solve your issue without migrating to https://github.com/jd/tenacity ;-)

**Comment by odedfos** [comment]
Thanks @bersace for all the good advice.
Nice to see there is a maintained library. Hopefully I'll switch to it when I get the time.

For the time being and for the sake of anyone using this library and who is searching for a more dynamic approach to retrying, this is my solution - use the Retry class I attached above but not as a context-manager but as a normal class similar to what you suggested:

```
retry_unreliable = Retry(do_something_unreliable, wait_fixed=2000)
retry_unreliable(do_something_arg)
```

This way you still get type checking, no need to patch the library (you can just place the class in your code) and the solution is more 'correct' in the sense that the 'with' statement cannot loop and doesn't benefit in any way.

**Comment by bersace** [comment]
Nice !

Is this issue still relevant ?
