### ISSUE TITLE
Add support for coroutines 

### ISSUE THREAD

**Issue by Pradhvan** [rholder/retrying#85]
```Python
@retry(stop_max_attempt_number=7)
async def stop_after_7_attempts():
    print "Stopping after 7 attempts"
```
It would great to have this feature where it works for coroutines too.

**Comment by lucasnad27** [comment]
tenacity is a fork of retrying that has async support. From their README:

> Tenacity is an Apache 2.0 licensed general-purpose retrying library, written in Python, to simplify the task of adding retry behavior to just about anything. It originates from a fork of retrying which is sadly no longer maintained. Tenacity isn’t api compatible with retrying but adds significant new functionality and fixes a number of longstanding bugs.
